phases {
  user_types {
    name: "Normal"
    ratio: 1
    min_wait_ms: 1000
    max_wait_ms: 1000
  }
  duration: 50
  num_users: 100
  hatch_rate_per_s: 30
}
phases {
  user_types {
    name: "Normal"
    ratio: 1
    min_wait_ms: 1000
    max_wait_ms: 1000
  }
  user_types {
    name: "Weekend"
    ratio: 2
    min_wait_ms: 1000
    max_wait_ms: 1000
  }
  duration: 20
  num_users: 200
  hatch_rate_per_s: 50
}
phases {
  user_types {
    name: "Normal"
    ratio: 1
    min_wait_ms: 1000
    max_wait_ms: 1000
  }
  user_types {
    name: "Holiday"
    ratio: 3
    min_wait_ms: 1000
    max_wait_ms: 1000
  }
  duration: 10
  num_users: 300
  hatch_rate_per_s: 100
}