---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../../pem
patches:
- path: deployment.yaml
  target:
    kind: Deployment
- path: job.yaml
  target:
    kind: Job
- path: statefulset.yaml
  target:
    kind: StatefulSet
- path: daemonset.yaml
  target:
    kind: DaemonSet
