/* global __CONFIG_AUTH0_DOMAIN__, __CONFIG_AUTH0_CLIENT_ID__, __CONFIG_DOMAIN_NAME__,
__CONFIG_LD_CLIENT_ID__, __SEGMENT_UI_WRITE_KEY__, __ANALYTICS_ENABLED__,
__ANNOUNCEMENT_ENABLED__, __ANNOUNCE_WIDGET_URL__, __CONTACT_ENABLED__ */
const AUTH0_DOMAIN = __CONFIG_AUTH0_DOMAIN__;
const AUTH0_CLIENT_ID = __CONFIG_AUTH0_CLIENT_ID__;
const DOMAIN_NAME = __CONFIG_DOMAIN_NAME__;
const LD_CLIENT_ID = __CONFIG_LD_CLIENT_ID__;
const SEGMENT_UI_WRITE_KEY = __SEGMENT_UI_WRITE_KEY__;
const ANALYTICS_ENABLED = __ANALYTICS_ENABLED__;
const ANNOUNCEMENT_ENABLED = __ANNOUNCEMENT_ENABLED__;
const ANNOUNCE_WIDGET_URL = __ANNOUNCE_WIDGET_URL__;
const CONTACT_ENABLED = __CONTACT_ENABLED__;

// There is a bug with using esnext + webpack-replace-plugin, where
// lines with an export and replacement will not compile properly.
// eslint-disable-next-line no-underscore-dangle
window.__PIXIE_FLAGS__ = {
  AUTH0_DOMAIN,
  AUTH0_CLIENT_ID,
  DOMAIN_NAME,
  SEGMENT_UI_WRITE_KEY,
  LD_CLIENT_ID,
  ANALYTICS_ENABLED,
  ANNOUNCEMENT_ENABLED,
  ANNOUNCE_WIDGET_URL,
  CONTACT_ENABLED,
};
