---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://10.32.0.106 --web-host=0.0.0.0 \
                      -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100; done"]
        ports:
        - containerPort: 8089
      nodeSelector:
        beta.kubernetes.io/os: linux
