---
version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
  - asciicheck
  - makezero
  - misspell
  - nakedret
  - nolintlint
  - nonamedreturns
  - predeclared
  - revive
  - whitespace
  settings:
    errcheck:
      exclude-functions:
      - io.Close
      - github.com/spf13/pflag.MarkHidden
      - github.com/spf13/viper.BindEnv
      - github.com/spf13/viper.BindPFlag
      - github.com/spf13/cobra.Help
      - github.com/spf13/cobra.MarkFlagRequired
      - github.com/spf13/cobra.Usage
      - (github.com/segmentio/analytics-go/v3.Client).Enqueue
      - database/sql.Rollback
      - github.com/nats-io/nats.go.Unsubscribe
    staticcheck:
      checks:
      - all
      - "-ST1005"  # ignore the "ST1005: error strings should not be capitalized" check
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
  - gofmt
  settings:
    goimports:
      local-prefixes:
      - px.dev
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
