---
version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
  - asciicheck
  - errcheck
  - govet
  - ineffassign
  - makezero
  - misspell
  - nakedret
  - nolintlint
  - nonamedreturns
  - predeclared
  - revive
  - staticcheck
  - unused
  - whitespace
  settings:
    errcheck:
      exclude-functions:
      - io.Close
      - (*github.com/spf13/pflag.FlagSet).MarkHidden
      - github.com/spf13/viper.BindEnv
      - github.com/spf13/viper.BindPFlag
      - github.com/spf13/viper.BindPFlags
      - (*github.com/spf13/cobra.Command).Help
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*github.com/spf13/cobra.Command).Usage
      - (github.com/segmentio/analytics-go/v3.Client).Enqueue
      - (*database/sql.Tx).Rollback
      - (*github.com/nats-io/nats.go.Subscription).Unsubscribe
    revive:
      rules:
      - name: unused-parameter
        disabled: true
    staticcheck:
      checks:
      - all
      - "-ST1005"  # ignore the "ST1005: error strings should not be capitalized" check
      - "-QF1008"  # ignore omit embedded fields from selector expression
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
  - gci
  - gofumpt
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(px.dev)
      custom-order: true
    goimports:
      local-prefixes:
      - px.dev
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
