---
codecov:
  branch: main

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
- "src/ui/.yarn"
- "src/ui/src/testing"
- "src/ui/src/types/generated"
- "third_party"
