---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  labels:
    name: http-server
spec:
  ports:
  - protocol: "TCP"
    port: 50051
    targetPort: 50051
  selector:
    name: go-http-server
