---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc-testing
replicas:
- name: api-server
  count: 3
- name: auth-server
  count: 3
- name: profile-server
  count: 3
- name: cloud-proxy
  count: 3
- name: project-manager-server
  count: 3
- name: vzmgr-server
  count: 1
- name: scriptmgr-server
  count: 3
resources:
- frontend_config.yaml
- cloud_ingress_managed_cert.yaml
- cloud_ingress_managed_cert_noslackin.yaml
- cloud_proxy_backend_config.yaml
- vzconn_backend_config.yaml
- ../base
- ../overlays/exposed_services_gclb
- ../overlays/plugin_job
patches:
- path: auth_deployment.yaml
- path: db_sidecar.yaml
  target:
    kind: Deployment
    labelSelector: db=pgsql
- path: bq_config.yaml
- path: support_access_config.yaml
- path: analytics_config.yaml
- path: contact_config.yaml
- path: db_config.yaml
- path: indexer_config.yaml
- path: service_config.yaml
- path: domain_config.yaml
- path: cloud_ingress_ip.yaml
- path: script_bundles_config.yaml
- path: proxy_envoy.yaml
