apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pixie-operator-subscription
  namespace: {{ .Values.olmOperatorNamespace }}
spec:
  channel: {{ .Values.olmBundleChannel }}
  name: pixie-operator
  source: pixie-operator-index
  sourceNamespace: {{ .Values.olmOperatorNamespace }}
  installPlanApproval: Automatic
  {{- if .Values.olmCatalogSource.nodeSelector }}
  config:
    nodeSelector: {{ .Values.olmCatalogSource.nodeSelector | toYaml | nindent 6 }}
  {{- end }}
