---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: px-grpc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grpc-server
  template:
    metadata:
      labels:
        name: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: gcr.io/pixie-oss/pixie-dev/src/stirling/testing/demo_apps/go_grpc_tls_pl/server:latest
        ports:
        - containerPort: 50400
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
