DROP INDEX idx_vizier_cluster_cluster_uid;
DROP INDEX idx_vizier_cluster_cluster_name;
DROP INDEX idx_vizier_cluster_org_id;

DROP INDEX idx_vizier_cluster_info_status;
DROP INDEX idx_vizier_cluster_info_last_heartbeat;
