homebrew_package 'python'
homebrew_package 'python3'
homebrew_package 'bazel'
homebrew_package 'go'
homebrew_package 'postgresql'
homebrew_package 'pyenv-virtualenv'
homebrew_package 'clang-format'
homebrew_package 'dep'

homebrew_cask 'docker-edge'
homebrew_cask 'minikube'
