---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: pl-monitoring
  component: vizier
kind: Kustomization
namespace: pl
resources:
- pem_daemonset.yaml
patches:
- path: arch_tolerations/daemonset.yaml
  target:
    kind: DaemonSet
