// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/carnot/planner/plannerpb/query_flags.proto

package plannerpb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	planpb "pixielabs.ai/pixielabs/src/carnot/planpb"
	proto2 "pixielabs.ai/pixielabs/src/common/base/proto"
	proto1 "pixielabs.ai/pixielabs/src/shared/types/proto"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryFlagsSpec struct {
	Flags []*QueryFlagsSpec_Flag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
}

func (m *QueryFlagsSpec) Reset()      { *m = QueryFlagsSpec{} }
func (*QueryFlagsSpec) ProtoMessage() {}
func (*QueryFlagsSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_786c9517dae463d8, []int{0}
}
func (m *QueryFlagsSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFlagsSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFlagsSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFlagsSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFlagsSpec.Merge(m, src)
}
func (m *QueryFlagsSpec) XXX_Size() int {
	return m.Size()
}
func (m *QueryFlagsSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFlagsSpec.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFlagsSpec proto.InternalMessageInfo

func (m *QueryFlagsSpec) GetFlags() []*QueryFlagsSpec_Flag {
	if m != nil {
		return m.Flags
	}
	return nil
}

type QueryFlagsSpec_Flag struct {
	DataType     proto1.DataType     `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=pl.types.DataType" json:"data_type,omitempty"`
	SemanticType proto1.SemanticType `protobuf:"varint,2,opt,name=semantic_type,json=semanticType,proto3,enum=pl.types.SemanticType" json:"semantic_type,omitempty"`
	Name         string              `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description  string              `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue *planpb.ScalarValue `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (m *QueryFlagsSpec_Flag) Reset()      { *m = QueryFlagsSpec_Flag{} }
func (*QueryFlagsSpec_Flag) ProtoMessage() {}
func (*QueryFlagsSpec_Flag) Descriptor() ([]byte, []int) {
	return fileDescriptor_786c9517dae463d8, []int{0, 0}
}
func (m *QueryFlagsSpec_Flag) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFlagsSpec_Flag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFlagsSpec_Flag.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFlagsSpec_Flag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFlagsSpec_Flag.Merge(m, src)
}
func (m *QueryFlagsSpec_Flag) XXX_Size() int {
	return m.Size()
}
func (m *QueryFlagsSpec_Flag) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFlagsSpec_Flag.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFlagsSpec_Flag proto.InternalMessageInfo

func (m *QueryFlagsSpec_Flag) GetDataType() proto1.DataType {
	if m != nil {
		return m.DataType
	}
	return proto1.DATA_TYPE_UNKNOWN
}

func (m *QueryFlagsSpec_Flag) GetSemanticType() proto1.SemanticType {
	if m != nil {
		return m.SemanticType
	}
	return proto1.ST_UNSPECIFIED
}

func (m *QueryFlagsSpec_Flag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryFlagsSpec_Flag) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *QueryFlagsSpec_Flag) GetDefaultValue() *planpb.ScalarValue {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

type QueryRequest struct {
	QueryStr   string                    `protobuf:"bytes,1,opt,name=query_str,json=queryStr,proto3" json:"query_str,omitempty"`
	FlagValues []*QueryRequest_FlagValue `protobuf:"bytes,2,rep,name=flag_values,json=flagValues,proto3" json:"flag_values,omitempty"`
}

func (m *QueryRequest) Reset()      { *m = QueryRequest{} }
func (*QueryRequest) ProtoMessage() {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_786c9517dae463d8, []int{1}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQueryStr() string {
	if m != nil {
		return m.QueryStr
	}
	return ""
}

func (m *QueryRequest) GetFlagValues() []*QueryRequest_FlagValue {
	if m != nil {
		return m.FlagValues
	}
	return nil
}

type QueryRequest_FlagValue struct {
	FlagName  string              `protobuf:"bytes,1,opt,name=flag_name,json=flagName,proto3" json:"flag_name,omitempty"`
	FlagValue *planpb.ScalarValue `protobuf:"bytes,2,opt,name=flag_value,json=flagValue,proto3" json:"flag_value,omitempty"`
}

func (m *QueryRequest_FlagValue) Reset()      { *m = QueryRequest_FlagValue{} }
func (*QueryRequest_FlagValue) ProtoMessage() {}
func (*QueryRequest_FlagValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_786c9517dae463d8, []int{1, 0}
}
func (m *QueryRequest_FlagValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRequest_FlagValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRequest_FlagValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRequest_FlagValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest_FlagValue.Merge(m, src)
}
func (m *QueryRequest_FlagValue) XXX_Size() int {
	return m.Size()
}
func (m *QueryRequest_FlagValue) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest_FlagValue.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest_FlagValue proto.InternalMessageInfo

func (m *QueryRequest_FlagValue) GetFlagName() string {
	if m != nil {
		return m.FlagName
	}
	return ""
}

func (m *QueryRequest_FlagValue) GetFlagValue() *planpb.ScalarValue {
	if m != nil {
		return m.FlagValue
	}
	return nil
}

type GetAvailableFlagsResult struct {
	QueryFlags *QueryFlagsSpec `protobuf:"bytes,1,opt,name=query_flags,json=queryFlags,proto3" json:"query_flags,omitempty"`
	Status     *proto2.Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *GetAvailableFlagsResult) Reset()      { *m = GetAvailableFlagsResult{} }
func (*GetAvailableFlagsResult) ProtoMessage() {}
func (*GetAvailableFlagsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_786c9517dae463d8, []int{2}
}
func (m *GetAvailableFlagsResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAvailableFlagsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAvailableFlagsResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAvailableFlagsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailableFlagsResult.Merge(m, src)
}
func (m *GetAvailableFlagsResult) XXX_Size() int {
	return m.Size()
}
func (m *GetAvailableFlagsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailableFlagsResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailableFlagsResult proto.InternalMessageInfo

func (m *GetAvailableFlagsResult) GetQueryFlags() *QueryFlagsSpec {
	if m != nil {
		return m.QueryFlags
	}
	return nil
}

func (m *GetAvailableFlagsResult) GetStatus() *proto2.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryFlagsSpec)(nil), "pl.carnot.compiler.plannerpb.QueryFlagsSpec")
	proto.RegisterType((*QueryFlagsSpec_Flag)(nil), "pl.carnot.compiler.plannerpb.QueryFlagsSpec.Flag")
	proto.RegisterType((*QueryRequest)(nil), "pl.carnot.compiler.plannerpb.QueryRequest")
	proto.RegisterType((*QueryRequest_FlagValue)(nil), "pl.carnot.compiler.plannerpb.QueryRequest.FlagValue")
	proto.RegisterType((*GetAvailableFlagsResult)(nil), "pl.carnot.compiler.plannerpb.GetAvailableFlagsResult")
}

func init() {
	proto.RegisterFile("src/carnot/planner/plannerpb/query_flags.proto", fileDescriptor_786c9517dae463d8)
}

var fileDescriptor_786c9517dae463d8 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbd, 0x8e, 0xd3, 0x4c,
	0x14, 0xf5, 0x64, 0xb3, 0xab, 0xf5, 0x75, 0x76, 0x8b, 0xf9, 0xa4, 0x0f, 0x2b, 0x2c, 0xa3, 0x28,
	0x55, 0x24, 0x90, 0x2d, 0x02, 0x1d, 0x48, 0x88, 0x15, 0x62, 0x2b, 0x90, 0x70, 0x80, 0x82, 0x26,
	0x9a, 0x38, 0x13, 0x88, 0xe4, 0xd8, 0xce, 0xcc, 0x78, 0xa5, 0x74, 0x3c, 0x02, 0x0d, 0xef, 0xc0,
	0xa3, 0x20, 0xaa, 0x94, 0x5b, 0x12, 0xa7, 0x41, 0x14, 0x68, 0x1f, 0x01, 0xcd, 0x9d, 0xd9, 0xac,
	0x69, 0xf8, 0xa9, 0x72, 0x7f, 0xce, 0xb9, 0xf7, 0xcc, 0xc9, 0x35, 0xc4, 0x4a, 0xa6, 0x71, 0xca,
	0x65, 0x5e, 0xe8, 0x38, 0x2d, 0x16, 0xe5, 0x3c, 0x13, 0x32, 0x2e, 0x33, 0x9e, 0xe7, 0x42, 0x96,
	0x93, 0x78, 0x59, 0x09, 0xb9, 0x1a, 0xcf, 0x32, 0xfe, 0x56, 0x45, 0xa5, 0x2c, 0x74, 0x41, 0x4f,
	0xca, 0x2c, 0xb2, 0xf8, 0xe8, 0x0a, 0x1f, 0xed, 0xf0, 0xdd, 0x3e, 0x8e, 0x2b, 0x16, 0x8b, 0x22,
	0x8f, 0x27, 0x5c, 0x89, 0x18, 0x49, 0xb1, 0xd2, 0x5c, 0x57, 0x6e, 0x82, 0xc5, 0xa8, 0x77, 0x5c,
	0x8a, 0x69, 0xac, 0x57, 0xa5, 0x50, 0x0e, 0x84, 0xb1, 0xc3, 0x9c, 0x34, 0x64, 0x99, 0xe9, 0xe5,
	0x04, 0x7f, 0x6c, 0xb7, 0xff, 0xa5, 0x05, 0xc7, 0x2f, 0x8c, 0xb2, 0xa7, 0x46, 0xd8, 0xa8, 0x14,
	0x29, 0x3d, 0x83, 0x7d, 0x54, 0x19, 0x92, 0xde, 0xde, 0x20, 0x18, 0xde, 0x8d, 0x7e, 0x27, 0x33,
	0xfa, 0x95, 0x1c, 0x99, 0x28, 0xb1, 0xfc, 0xee, 0x0f, 0x02, 0x6d, 0x93, 0xd3, 0x18, 0xfc, 0x29,
	0xd7, 0x7c, 0x6c, 0x64, 0x85, 0xa4, 0x47, 0x06, 0xc7, 0x43, 0x6a, 0xa6, 0x5a, 0x99, 0x4f, 0xb8,
	0xe6, 0x2f, 0x57, 0xa5, 0x48, 0x0e, 0xa7, 0x2e, 0xa2, 0x0f, 0xe0, 0x48, 0x89, 0x05, 0xcf, 0xf5,
	0x3c, 0xb5, 0xa4, 0x16, 0x92, 0xfe, 0xbf, 0x26, 0x8d, 0x5c, 0x1b, 0x89, 0x1d, 0xd5, 0xc8, 0x28,
	0x85, 0x76, 0xce, 0x17, 0x22, 0xdc, 0xeb, 0x91, 0x81, 0x9f, 0x60, 0x4c, 0x7b, 0x10, 0x4c, 0x85,
	0x4a, 0xe5, 0xbc, 0xd4, 0xf3, 0x22, 0x0f, 0xdb, 0xd8, 0x6a, 0x96, 0xe8, 0x29, 0x1c, 0x4d, 0xc5,
	0x8c, 0x57, 0x99, 0x1e, 0x9f, 0xf3, 0xac, 0x12, 0xe1, 0x7e, 0x8f, 0x0c, 0x82, 0xe1, 0xad, 0xc6,
	0xeb, 0xad, 0x7b, 0xd1, 0x28, 0xe5, 0x19, 0x97, 0xaf, 0x0d, 0x28, 0xe9, 0x38, 0x0e, 0x66, 0xfd,
	0xef, 0x04, 0x3a, 0xe8, 0x47, 0x22, 0x96, 0x95, 0x50, 0x9a, 0xde, 0x04, 0xdf, 0xfe, 0xed, 0x4a,
	0x4b, 0x7c, 0xb8, 0x9f, 0x1c, 0x62, 0x61, 0xa4, 0x25, 0x7d, 0x05, 0x81, 0xf1, 0xc9, 0xae, 0x53,
	0x61, 0x0b, 0xdd, 0xbe, 0xff, 0x17, 0x6e, 0xbb, 0xe9, 0xe8, 0xb5, 0x95, 0x01, 0xb3, 0xab, 0x50,
	0x75, 0x67, 0xe0, 0xef, 0x1a, 0x46, 0x00, 0xee, 0x40, 0x43, 0x9c, 0x00, 0x53, 0x78, 0x6e, 0x4c,
	0x79, 0x08, 0x70, 0x2d, 0x00, 0x2d, 0xfe, 0xe3, 0x7b, 0xfd, 0xdd, 0xa2, 0xfe, 0x47, 0x02, 0x37,
	0xce, 0x84, 0x7e, 0x7c, 0xce, 0xe7, 0x19, 0x9f, 0x64, 0x02, 0x6f, 0x20, 0x11, 0xaa, 0xca, 0x34,
	0x7d, 0x06, 0x41, 0xe3, 0xdc, 0x71, 0x71, 0x30, 0xbc, 0xf3, 0x2f, 0x87, 0x94, 0xc0, 0x72, 0x97,
	0xd3, 0xdb, 0x70, 0x60, 0xcf, 0xde, 0x89, 0xfc, 0xcf, 0x4c, 0xb2, 0x15, 0xa3, 0x0f, 0x83, 0xc4,
	0x41, 0x4e, 0x1f, 0xad, 0x37, 0xcc, 0xbb, 0xd8, 0x30, 0xef, 0x72, 0xc3, 0xc8, 0xfb, 0x9a, 0x91,
	0x4f, 0x35, 0x23, 0x9f, 0x6b, 0x46, 0xd6, 0x35, 0x23, 0x5f, 0x6b, 0x46, 0xbe, 0xd5, 0xcc, 0xbb,
	0xac, 0x19, 0xf9, 0xb0, 0x65, 0xde, 0x7a, 0xcb, 0xbc, 0x8b, 0x2d, 0xf3, 0xde, 0xf8, 0x3b, 0x21,
	0x93, 0x03, 0xfc, 0x32, 0xee, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x55, 0xc5, 0x2d, 0x23, 0xd0,
	0x03, 0x00, 0x00,
}

func (this *QueryFlagsSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryFlagsSpec)
	if !ok {
		that2, ok := that.(QueryFlagsSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Flags) != len(that1.Flags) {
		return false
	}
	for i := range this.Flags {
		if !this.Flags[i].Equal(that1.Flags[i]) {
			return false
		}
	}
	return true
}
func (this *QueryFlagsSpec_Flag) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryFlagsSpec_Flag)
	if !ok {
		that2, ok := that.(QueryFlagsSpec_Flag)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DataType != that1.DataType {
		return false
	}
	if this.SemanticType != that1.SemanticType {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if !this.DefaultValue.Equal(that1.DefaultValue) {
		return false
	}
	return true
}
func (this *QueryRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryRequest)
	if !ok {
		that2, ok := that.(QueryRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.QueryStr != that1.QueryStr {
		return false
	}
	if len(this.FlagValues) != len(that1.FlagValues) {
		return false
	}
	for i := range this.FlagValues {
		if !this.FlagValues[i].Equal(that1.FlagValues[i]) {
			return false
		}
	}
	return true
}
func (this *QueryRequest_FlagValue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryRequest_FlagValue)
	if !ok {
		that2, ok := that.(QueryRequest_FlagValue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FlagName != that1.FlagName {
		return false
	}
	if !this.FlagValue.Equal(that1.FlagValue) {
		return false
	}
	return true
}
func (this *GetAvailableFlagsResult) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetAvailableFlagsResult)
	if !ok {
		that2, ok := that.(GetAvailableFlagsResult)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.QueryFlags.Equal(that1.QueryFlags) {
		return false
	}
	if !this.Status.Equal(that1.Status) {
		return false
	}
	return true
}
func (this *QueryFlagsSpec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&plannerpb.QueryFlagsSpec{")
	if this.Flags != nil {
		s = append(s, "Flags: "+fmt.Sprintf("%#v", this.Flags)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *QueryFlagsSpec_Flag) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&plannerpb.QueryFlagsSpec_Flag{")
	s = append(s, "DataType: "+fmt.Sprintf("%#v", this.DataType)+",\n")
	s = append(s, "SemanticType: "+fmt.Sprintf("%#v", this.SemanticType)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	if this.DefaultValue != nil {
		s = append(s, "DefaultValue: "+fmt.Sprintf("%#v", this.DefaultValue)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *QueryRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&plannerpb.QueryRequest{")
	s = append(s, "QueryStr: "+fmt.Sprintf("%#v", this.QueryStr)+",\n")
	if this.FlagValues != nil {
		s = append(s, "FlagValues: "+fmt.Sprintf("%#v", this.FlagValues)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *QueryRequest_FlagValue) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&plannerpb.QueryRequest_FlagValue{")
	s = append(s, "FlagName: "+fmt.Sprintf("%#v", this.FlagName)+",\n")
	if this.FlagValue != nil {
		s = append(s, "FlagValue: "+fmt.Sprintf("%#v", this.FlagValue)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetAvailableFlagsResult) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&plannerpb.GetAvailableFlagsResult{")
	if this.QueryFlags != nil {
		s = append(s, "QueryFlags: "+fmt.Sprintf("%#v", this.QueryFlags)+",\n")
	}
	if this.Status != nil {
		s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringQueryFlags(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *QueryFlagsSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFlagsSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFlagsSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Flags) > 0 {
		for iNdEx := len(m.Flags) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Flags[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryFlags(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFlagsSpec_Flag) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFlagsSpec_Flag) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFlagsSpec_Flag) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DefaultValue != nil {
		{
			size, err := m.DefaultValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryFlags(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintQueryFlags(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQueryFlags(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SemanticType != 0 {
		i = encodeVarintQueryFlags(dAtA, i, uint64(m.SemanticType))
		i--
		dAtA[i] = 0x10
	}
	if m.DataType != 0 {
		i = encodeVarintQueryFlags(dAtA, i, uint64(m.DataType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FlagValues) > 0 {
		for iNdEx := len(m.FlagValues) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FlagValues[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryFlags(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.QueryStr) > 0 {
		i -= len(m.QueryStr)
		copy(dAtA[i:], m.QueryStr)
		i = encodeVarintQueryFlags(dAtA, i, uint64(len(m.QueryStr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRequest_FlagValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRequest_FlagValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRequest_FlagValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FlagValue != nil {
		{
			size, err := m.FlagValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryFlags(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FlagName) > 0 {
		i -= len(m.FlagName)
		copy(dAtA[i:], m.FlagName)
		i = encodeVarintQueryFlags(dAtA, i, uint64(len(m.FlagName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAvailableFlagsResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAvailableFlagsResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAvailableFlagsResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryFlags(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.QueryFlags != nil {
		{
			size, err := m.QueryFlags.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryFlags(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryFlags(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryFlags(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryFlagsSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Flags) > 0 {
		for _, e := range m.Flags {
			l = e.Size()
			n += 1 + l + sovQueryFlags(uint64(l))
		}
	}
	return n
}

func (m *QueryFlagsSpec_Flag) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DataType != 0 {
		n += 1 + sovQueryFlags(uint64(m.DataType))
	}
	if m.SemanticType != 0 {
		n += 1 + sovQueryFlags(uint64(m.SemanticType))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	if m.DefaultValue != nil {
		l = m.DefaultValue.Size()
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	return n
}

func (m *QueryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryStr)
	if l > 0 {
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	if len(m.FlagValues) > 0 {
		for _, e := range m.FlagValues {
			l = e.Size()
			n += 1 + l + sovQueryFlags(uint64(l))
		}
	}
	return n
}

func (m *QueryRequest_FlagValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FlagName)
	if l > 0 {
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	if m.FlagValue != nil {
		l = m.FlagValue.Size()
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	return n
}

func (m *GetAvailableFlagsResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.QueryFlags != nil {
		l = m.QueryFlags.Size()
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQueryFlags(uint64(l))
	}
	return n
}

func sovQueryFlags(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryFlags(x uint64) (n int) {
	return sovQueryFlags(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *QueryFlagsSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForFlags := "[]*QueryFlagsSpec_Flag{"
	for _, f := range this.Flags {
		repeatedStringForFlags += strings.Replace(fmt.Sprintf("%v", f), "QueryFlagsSpec_Flag", "QueryFlagsSpec_Flag", 1) + ","
	}
	repeatedStringForFlags += "}"
	s := strings.Join([]string{`&QueryFlagsSpec{`,
		`Flags:` + repeatedStringForFlags + `,`,
		`}`,
	}, "")
	return s
}
func (this *QueryFlagsSpec_Flag) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&QueryFlagsSpec_Flag{`,
		`DataType:` + fmt.Sprintf("%v", this.DataType) + `,`,
		`SemanticType:` + fmt.Sprintf("%v", this.SemanticType) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`DefaultValue:` + strings.Replace(fmt.Sprintf("%v", this.DefaultValue), "ScalarValue", "planpb.ScalarValue", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *QueryRequest) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForFlagValues := "[]*QueryRequest_FlagValue{"
	for _, f := range this.FlagValues {
		repeatedStringForFlagValues += strings.Replace(fmt.Sprintf("%v", f), "QueryRequest_FlagValue", "QueryRequest_FlagValue", 1) + ","
	}
	repeatedStringForFlagValues += "}"
	s := strings.Join([]string{`&QueryRequest{`,
		`QueryStr:` + fmt.Sprintf("%v", this.QueryStr) + `,`,
		`FlagValues:` + repeatedStringForFlagValues + `,`,
		`}`,
	}, "")
	return s
}
func (this *QueryRequest_FlagValue) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&QueryRequest_FlagValue{`,
		`FlagName:` + fmt.Sprintf("%v", this.FlagName) + `,`,
		`FlagValue:` + strings.Replace(fmt.Sprintf("%v", this.FlagValue), "ScalarValue", "planpb.ScalarValue", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetAvailableFlagsResult) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetAvailableFlagsResult{`,
		`QueryFlags:` + strings.Replace(this.QueryFlags.String(), "QueryFlagsSpec", "QueryFlagsSpec", 1) + `,`,
		`Status:` + strings.Replace(fmt.Sprintf("%v", this.Status), "Status", "proto2.Status", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringQueryFlags(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *QueryFlagsSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFlagsSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFlagsSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flags = append(m.Flags, &QueryFlagsSpec_Flag{})
			if err := m.Flags[len(m.Flags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFlagsSpec_Flag) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Flag: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Flag: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataType", wireType)
			}
			m.DataType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataType |= proto1.DataType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SemanticType", wireType)
			}
			m.SemanticType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SemanticType |= proto1.SemanticType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DefaultValue == nil {
				m.DefaultValue = &planpb.ScalarValue{}
			}
			if err := m.DefaultValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryStr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryStr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlagValues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FlagValues = append(m.FlagValues, &QueryRequest_FlagValue{})
			if err := m.FlagValues[len(m.FlagValues)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRequest_FlagValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlagValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlagValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlagName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FlagName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FlagValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FlagValue == nil {
				m.FlagValue = &planpb.ScalarValue{}
			}
			if err := m.FlagValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAvailableFlagsResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAvailableFlagsResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAvailableFlagsResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryFlags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QueryFlags == nil {
				m.QueryFlags = &QueryFlagsSpec{}
			}
			if err := m.QueryFlags.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryFlags
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &proto2.Status{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryFlags(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQueryFlags
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryFlags(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryFlags
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryFlags
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryFlags
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthQueryFlags
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowQueryFlags
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipQueryFlags(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthQueryFlags
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthQueryFlags = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryFlags   = fmt.Errorf("proto: integer overflow")
)
