// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/cloud/vzconn/vzconnpb/service.proto

package vzconnpb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	_ "pixielabs.ai/pixielabs/src/common/uuid/proto"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CloudConnectRequest struct {
	Topic string     `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg   *types.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *CloudConnectRequest) Reset()      { *m = CloudConnectRequest{} }
func (*CloudConnectRequest) ProtoMessage() {}
func (*CloudConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_935788a74a5b0e3d, []int{0}
}
func (m *CloudConnectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CloudConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CloudConnectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CloudConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudConnectRequest.Merge(m, src)
}
func (m *CloudConnectRequest) XXX_Size() int {
	return m.Size()
}
func (m *CloudConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloudConnectRequest proto.InternalMessageInfo

func (m *CloudConnectRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CloudConnectRequest) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

type CloudConnectResponse struct {
	Topic string     `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg   *types.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *CloudConnectResponse) Reset()      { *m = CloudConnectResponse{} }
func (*CloudConnectResponse) ProtoMessage() {}
func (*CloudConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_935788a74a5b0e3d, []int{1}
}
func (m *CloudConnectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CloudConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CloudConnectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CloudConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudConnectResponse.Merge(m, src)
}
func (m *CloudConnectResponse) XXX_Size() int {
	return m.Size()
}
func (m *CloudConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloudConnectResponse proto.InternalMessageInfo

func (m *CloudConnectResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *CloudConnectResponse) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudConnectRequest)(nil), "pl.services.CloudConnectRequest")
	proto.RegisterType((*CloudConnectResponse)(nil), "pl.services.CloudConnectResponse")
}

func init() {
	proto.RegisterFile("src/cloud/vzconn/vzconnpb/service.proto", fileDescriptor_935788a74a5b0e3d)
}

var fileDescriptor_935788a74a5b0e3d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbf, 0x4e, 0x02, 0x31,
	0x1c, 0xc7, 0x5b, 0x8d, 0x26, 0x16, 0x5d, 0x4e, 0x06, 0x64, 0x68, 0x4e, 0x06, 0x65, 0xb1, 0x35,
	0x38, 0x19, 0x27, 0xe5, 0x0d, 0xc0, 0x98, 0xc8, 0xc6, 0x95, 0x7a, 0xd6, 0xdc, 0xf5, 0x77, 0xd2,
	0x3b, 0x22, 0x4e, 0x3e, 0x82, 0x8f, 0xe1, 0xa3, 0x38, 0x32, 0x32, 0x4a, 0x59, 0x1c, 0x79, 0x04,
	0x43, 0x0b, 0x8a, 0x89, 0xba, 0x38, 0xdd, 0xf7, 0x7b, 0xfd, 0xf6, 0xf3, 0xfb, 0x93, 0x92, 0x43,
	0xd3, 0x17, 0x5c, 0x24, 0x50, 0xf4, 0xf8, 0xe0, 0x51, 0x80, 0xd6, 0x8b, 0x4f, 0x16, 0x71, 0x23,
	0xfb, 0x03, 0x25, 0x24, 0xcb, 0xfa, 0x90, 0x43, 0x50, 0xca, 0x12, 0xb6, 0xf8, 0x63, 0xaa, 0x47,
	0xb1, 0xca, 0x6f, 0x8b, 0x88, 0x09, 0x48, 0x79, 0x0c, 0x31, 0x70, 0x97, 0x89, 0x8a, 0x1b, 0xe7,
	0x9c, 0x71, 0xca, 0xdf, 0xad, 0x86, 0xae, 0x08, 0xa4, 0x29, 0x68, 0x5e, 0x14, 0xaa, 0xe7, 0xe3,
	0x4e, 0x2e, 0x12, 0x7b, 0x31, 0x40, 0x9c, 0xc8, 0x2f, 0x4e, 0x57, 0x0f, 0xfd, 0x51, 0xad, 0x4d,
	0x76, 0x9b, 0xf3, 0xfe, 0x9a, 0xa0, 0xb5, 0x14, 0x79, 0x4b, 0xde, 0x17, 0xd2, 0xe4, 0x41, 0x99,
	0x6c, 0xe4, 0x90, 0x29, 0x51, 0xc1, 0x21, 0xae, 0x6f, 0xb5, 0xbc, 0x09, 0x0e, 0xc8, 0x7a, 0x6a,
	0xe2, 0xca, 0x5a, 0x88, 0xeb, 0xa5, 0x46, 0x99, 0x79, 0x2a, 0x5b, 0x52, 0xd9, 0xb9, 0x1e, 0xb6,
	0xe6, 0x81, 0xda, 0x25, 0x29, 0x7f, 0x87, 0x9a, 0x0c, 0xb4, 0x91, 0xff, 0xa3, 0x36, 0xee, 0xc8,
	0xce, 0x55, 0x67, 0x8e, 0x6c, 0xfb, 0x45, 0x05, 0xd7, 0x64, 0x7b, 0xb5, 0x4c, 0x10, 0xb2, 0x95,
	0x2d, 0xb2, 0x1f, 0xc6, 0xaa, 0xee, 0xff, 0x91, 0xf0, 0x3d, 0xd6, 0x50, 0x1d, 0x1f, 0xe3, 0x0b,
	0x18, 0x4d, 0x28, 0x1a, 0x4f, 0x28, 0x9a, 0x4d, 0x28, 0x7e, 0xb2, 0x14, 0xbf, 0x58, 0x8a, 0x5f,
	0x2d, 0xc5, 0x23, 0x4b, 0xf1, 0x9b, 0xa5, 0xf8, 0xdd, 0x52, 0x34, 0xb3, 0x14, 0x3f, 0x4f, 0x29,
	0x1a, 0x4d, 0x29, 0x1a, 0x4f, 0x29, 0xea, 0x9c, 0x66, 0xea, 0x41, 0xc9, 0xa4, 0x1b, 0x19, 0xd6,
	0x55, 0xfc, 0xd3, 0xf0, 0x5f, 0x5f, 0xc1, 0xd9, 0x52, 0x44, 0x9b, 0x6e, 0xde, 0x93, 0x8f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0xcc, 0x49, 0x7d, 0x32, 0x02, 0x00, 0x00,
}

func (this *CloudConnectRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CloudConnectRequest)
	if !ok {
		that2, ok := that.(CloudConnectRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Topic != that1.Topic {
		return false
	}
	if !this.Msg.Equal(that1.Msg) {
		return false
	}
	return true
}
func (this *CloudConnectResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CloudConnectResponse)
	if !ok {
		that2, ok := that.(CloudConnectResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Topic != that1.Topic {
		return false
	}
	if !this.Msg.Equal(that1.Msg) {
		return false
	}
	return true
}
func (this *CloudConnectRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&vzconnpb.CloudConnectRequest{")
	s = append(s, "Topic: "+fmt.Sprintf("%#v", this.Topic)+",\n")
	if this.Msg != nil {
		s = append(s, "Msg: "+fmt.Sprintf("%#v", this.Msg)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CloudConnectResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&vzconnpb.CloudConnectResponse{")
	s = append(s, "Topic: "+fmt.Sprintf("%#v", this.Topic)+",\n")
	if this.Msg != nil {
		s = append(s, "Msg: "+fmt.Sprintf("%#v", this.Msg)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringService(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VZConnServiceClient is the client API for VZConnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VZConnServiceClient interface {
	CloudConnect(ctx context.Context, opts ...grpc.CallOption) (VZConnService_CloudConnectClient, error)
}

type vZConnServiceClient struct {
	cc *grpc.ClientConn
}

func NewVZConnServiceClient(cc *grpc.ClientConn) VZConnServiceClient {
	return &vZConnServiceClient{cc}
}

func (c *vZConnServiceClient) CloudConnect(ctx context.Context, opts ...grpc.CallOption) (VZConnService_CloudConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VZConnService_serviceDesc.Streams[0], "/pl.services.VZConnService/CloudConnect", opts...)
	if err != nil {
		return nil, err
	}
	x := &vZConnServiceCloudConnectClient{stream}
	return x, nil
}

type VZConnService_CloudConnectClient interface {
	Send(*CloudConnectRequest) error
	Recv() (*CloudConnectResponse, error)
	grpc.ClientStream
}

type vZConnServiceCloudConnectClient struct {
	grpc.ClientStream
}

func (x *vZConnServiceCloudConnectClient) Send(m *CloudConnectRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vZConnServiceCloudConnectClient) Recv() (*CloudConnectResponse, error) {
	m := new(CloudConnectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VZConnServiceServer is the server API for VZConnService service.
type VZConnServiceServer interface {
	CloudConnect(VZConnService_CloudConnectServer) error
}

func RegisterVZConnServiceServer(s *grpc.Server, srv VZConnServiceServer) {
	s.RegisterService(&_VZConnService_serviceDesc, srv)
}

func _VZConnService_CloudConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VZConnServiceServer).CloudConnect(&vZConnServiceCloudConnectServer{stream})
}

type VZConnService_CloudConnectServer interface {
	Send(*CloudConnectResponse) error
	Recv() (*CloudConnectRequest, error)
	grpc.ServerStream
}

type vZConnServiceCloudConnectServer struct {
	grpc.ServerStream
}

func (x *vZConnServiceCloudConnectServer) Send(m *CloudConnectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vZConnServiceCloudConnectServer) Recv() (*CloudConnectRequest, error) {
	m := new(CloudConnectRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VZConnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pl.services.VZConnService",
	HandlerType: (*VZConnServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CloudConnect",
			Handler:       _VZConnService_CloudConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/cloud/vzconn/vzconnpb/service.proto",
}

func (m *CloudConnectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CloudConnectRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Topic) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(len(m.Topic)))
		i += copy(dAtA[i:], m.Topic)
	}
	if m.Msg != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Msg.Size()))
		n1, err := m.Msg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *CloudConnectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CloudConnectResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Topic) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(len(m.Topic)))
		i += copy(dAtA[i:], m.Topic)
	}
	if m.Msg != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Msg.Size()))
		n2, err := m.Msg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CloudConnectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Topic)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func (m *CloudConnectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Topic)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovService(uint64(l))
	}
	return n
}

func sovService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CloudConnectRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CloudConnectRequest{`,
		`Topic:` + fmt.Sprintf("%v", this.Topic) + `,`,
		`Msg:` + strings.Replace(fmt.Sprintf("%v", this.Msg), "Any", "types.Any", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CloudConnectResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CloudConnectResponse{`,
		`Topic:` + fmt.Sprintf("%v", this.Topic) + `,`,
		`Msg:` + strings.Replace(fmt.Sprintf("%v", this.Msg), "Any", "types.Any", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CloudConnectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CloudConnectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CloudConnectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CloudConnectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CloudConnectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CloudConnectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topic = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthService
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService   = fmt.Errorf("proto: integer overflow")
)
