---
name: sign-artifacts
description: Sign all artifacts in the given directory using the provided GPG key.
inputs:
  artifacts-dir:
    description: 'Directory with artifacts to sign'
    required: true
  skip-shas:
    description: 'Whether to skip signing of sha256 files'
    default: 'true'
  BUILDBOT_GPG_KEY_ID:
    description: 'GPG key ID of key to sign with'
    required: true
  BUILDBOT_GPG_KEY_B64:
    description: 'GPG private key base64 encoded'
    required: true
runs:
  using: "composite"
  steps:
  - name: Import GPG key
    shell: bash
    env:
      BUILDBOT_GPG_KEY_B64: ${{ inputs.BUILDBOT_GPG_KEY_B64 }}
    run: |
      echo "${BUILDBOT_GPG_KEY_B64}" | base64 --decode | gpg --no-tty --batch --import
  - name: Sign Artifacts
    shell: bash
    env:
      ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
      SKIP_SHAS: ${{ inputs.skip-shas }}
      BUILDBOT_GPG_KEY_ID: ${{ inputs.BUILDBOT_GPG_KEY_ID }}
    # yamllint disable rule:indentation
    run: |
      for artifact in "${ARTIFACTS_DIR}/"*; do
        if [[ "${SKIP_SHAS}" == "true" ]] && [[ "${artifact}" == *".sha256" ]]; then
          continue
        fi
        gpg --no-tty --batch --yes --local-user "${BUILDBOT_GPG_KEY_ID}" --armor --detach-sign "${artifact}"
      done
    # yamllint enable rule:indentation
