---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-manager-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: project-manager-server
  template:
    metadata:
      labels:
        name: project-manager-server
    spec:
      containers:
      - name: project-manager-server
        imagePullPolicy: IfNotPresent
        image: cloud-project_manager_server_image
        ports:
        - containerPort: 50300
          name: http2
        - containerPort: 50301
          name: metrics-http
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50300
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50300
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_USERNAME
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_PASSWORD
        volumeMounts:
        - name: certs
          mountPath: /certs
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 10100
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        runAsUser: 10100
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
