---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-reader
  namespace: testing-ro
spec:
  selector:
    matchLabels:
      name: db-reader
  template:
    metadata:
      labels:
        name: db-reader
    spec:
      containers:
      # TODO(ddelnano): This image was rebuilt from https://github.com/docker-library/postgres 14-alpine
      # to remediate a critical vulnerability. Switch back to upstream once fixed.
      # yamllint disable-line rule:line-length
      - image: ghcr.io/pixie-io/postgres:14-alpine-pl1@sha256:237c5fcf79b230979e12fe02f46e0ad29565b4ecb7cb15047197cbb9a6549e8d
        imagePullPolicy: IfNotPresent
        name: psql
        command: ["bash"]
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      # yamllint disable-line rule:line-length
      - image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3@sha256:698174c37a5d4da797123a20bd5dc2b70fcaeae63c4cd634bdc9a70ce3282cbf
        args:
        - "--private-ip"
        - "--auto-iam-authn"
        - "--credentials-file=/secrets/cloudsql/db_service_account.json"
        - "pl-pixies:us-west1:pixie-cloud-testing-db-pg13"
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: pl-db-secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pl-db-secrets
        secret:
          defaultMode: 420
          secretName: pl-db-ro-secrets
