// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/carnot/compiler/compilerpb/distributed_plan.proto

package compilerpb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	planpb "pixielabs.ai/pixielabs/src/carnot/planpb"
	proto1 "pixielabs.ai/pixielabs/src/table_store/proto"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CarnotInfo struct {
	QueryBrokerAddress   string       `protobuf:"bytes,1,opt,name=query_broker_address,json=queryBrokerAddress,proto3" json:"query_broker_address,omitempty"`
	HasGrpcServer        bool         `protobuf:"varint,2,opt,name=has_grpc_server,json=hasGrpcServer,proto3" json:"has_grpc_server,omitempty"`
	GrpcAddress          string       `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	HasDataStore         bool         `protobuf:"varint,4,opt,name=has_data_store,json=hasDataStore,proto3" json:"has_data_store,omitempty"`
	ProcessesData        bool         `protobuf:"varint,5,opt,name=processes_data,json=processesData,proto3" json:"processes_data,omitempty"`
	AcceptsRemoteSources bool         `protobuf:"varint,6,opt,name=accepts_remote_sources,json=acceptsRemoteSources,proto3" json:"accepts_remote_sources,omitempty"`
	TableInfo            []*TableInfo `protobuf:"bytes,7,rep,name=table_info,json=tableInfo,proto3" json:"table_info,omitempty"`
}

func (m *CarnotInfo) Reset()      { *m = CarnotInfo{} }
func (*CarnotInfo) ProtoMessage() {}
func (*CarnotInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f78e8be07824f1b8, []int{0}
}
func (m *CarnotInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CarnotInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CarnotInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CarnotInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarnotInfo.Merge(m, src)
}
func (m *CarnotInfo) XXX_Size() int {
	return m.Size()
}
func (m *CarnotInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CarnotInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CarnotInfo proto.InternalMessageInfo

func (m *CarnotInfo) GetQueryBrokerAddress() string {
	if m != nil {
		return m.QueryBrokerAddress
	}
	return ""
}

func (m *CarnotInfo) GetHasGrpcServer() bool {
	if m != nil {
		return m.HasGrpcServer
	}
	return false
}

func (m *CarnotInfo) GetGrpcAddress() string {
	if m != nil {
		return m.GrpcAddress
	}
	return ""
}

func (m *CarnotInfo) GetHasDataStore() bool {
	if m != nil {
		return m.HasDataStore
	}
	return false
}

func (m *CarnotInfo) GetProcessesData() bool {
	if m != nil {
		return m.ProcessesData
	}
	return false
}

func (m *CarnotInfo) GetAcceptsRemoteSources() bool {
	if m != nil {
		return m.AcceptsRemoteSources
	}
	return false
}

func (m *CarnotInfo) GetTableInfo() []*TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type TableInfo struct {
	Table            string           `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Relation         *proto1.Relation `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	TabletizationKey string           `protobuf:"bytes,3,opt,name=tabletization_key,json=tabletizationKey,proto3" json:"tabletization_key,omitempty"`
	Tablets          []string         `protobuf:"bytes,4,rep,name=tablets,proto3" json:"tablets,omitempty"`
}

func (m *TableInfo) Reset()      { *m = TableInfo{} }
func (*TableInfo) ProtoMessage() {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f78e8be07824f1b8, []int{1}
}
func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return m.Size()
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

func (m *TableInfo) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *TableInfo) GetRelation() *proto1.Relation {
	if m != nil {
		return m.Relation
	}
	return nil
}

func (m *TableInfo) GetTabletizationKey() string {
	if m != nil {
		return m.TabletizationKey
	}
	return ""
}

func (m *TableInfo) GetTablets() []string {
	if m != nil {
		return m.Tablets
	}
	return nil
}

type DistributedState struct {
	CarnotInfo []*CarnotInfo `protobuf:"bytes,1,rep,name=carnot_info,json=carnotInfo,proto3" json:"carnot_info,omitempty"`
}

func (m *DistributedState) Reset()      { *m = DistributedState{} }
func (*DistributedState) ProtoMessage() {}
func (*DistributedState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f78e8be07824f1b8, []int{2}
}
func (m *DistributedState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DistributedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DistributedState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DistributedState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributedState.Merge(m, src)
}
func (m *DistributedState) XXX_Size() int {
	return m.Size()
}
func (m *DistributedState) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributedState.DiscardUnknown(m)
}

var xxx_messageInfo_DistributedState proto.InternalMessageInfo

func (m *DistributedState) GetCarnotInfo() []*CarnotInfo {
	if m != nil {
		return m.CarnotInfo
	}
	return nil
}

type DistributedPlan struct {
	QbAddressToPlan  map[string]*planpb.Plan `protobuf:"bytes,1,rep,name=qb_address_to_plan,json=qbAddressToPlan,proto3" json:"qb_address_to_plan,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	QbAddressToDagId map[string]uint64       `protobuf:"bytes,2,rep,name=qb_address_to_dag_id,json=qbAddressToDagId,proto3" json:"qb_address_to_dag_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Dag              *planpb.DAG             `protobuf:"bytes,3,opt,name=dag,proto3" json:"dag,omitempty"`
}

func (m *DistributedPlan) Reset()      { *m = DistributedPlan{} }
func (*DistributedPlan) ProtoMessage() {}
func (*DistributedPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_f78e8be07824f1b8, []int{3}
}
func (m *DistributedPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DistributedPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DistributedPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DistributedPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributedPlan.Merge(m, src)
}
func (m *DistributedPlan) XXX_Size() int {
	return m.Size()
}
func (m *DistributedPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributedPlan.DiscardUnknown(m)
}

var xxx_messageInfo_DistributedPlan proto.InternalMessageInfo

func (m *DistributedPlan) GetQbAddressToPlan() map[string]*planpb.Plan {
	if m != nil {
		return m.QbAddressToPlan
	}
	return nil
}

func (m *DistributedPlan) GetQbAddressToDagId() map[string]uint64 {
	if m != nil {
		return m.QbAddressToDagId
	}
	return nil
}

func (m *DistributedPlan) GetDag() *planpb.DAG {
	if m != nil {
		return m.Dag
	}
	return nil
}

func init() {
	proto.RegisterType((*CarnotInfo)(nil), "pl.carnot.compiler.compilerpb.CarnotInfo")
	proto.RegisterType((*TableInfo)(nil), "pl.carnot.compiler.compilerpb.TableInfo")
	proto.RegisterType((*DistributedState)(nil), "pl.carnot.compiler.compilerpb.DistributedState")
	proto.RegisterType((*DistributedPlan)(nil), "pl.carnot.compiler.compilerpb.DistributedPlan")
	proto.RegisterMapType((map[string]uint64)(nil), "pl.carnot.compiler.compilerpb.DistributedPlan.QbAddressToDagIdEntry")
	proto.RegisterMapType((map[string]*planpb.Plan)(nil), "pl.carnot.compiler.compilerpb.DistributedPlan.QbAddressToPlanEntry")
}

func init() {
	proto.RegisterFile("src/carnot/compiler/compilerpb/distributed_plan.proto", fileDescriptor_f78e8be07824f1b8)
}

var fileDescriptor_f78e8be07824f1b8 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x8d, 0x93, 0x7e, 0xe5, 0xa6, 0xaf, 0xcd, 0x1b, 0xa5, 0x95, 0x15, 0xbd, 0x37, 0x4a, 0xa3,
	0xf7, 0x20, 0x08, 0xe4, 0xa0, 0x02, 0x12, 0x42, 0x42, 0xa2, 0x6d, 0x50, 0x55, 0xd8, 0x80, 0xd3,
	0x55, 0x17, 0x58, 0x63, 0x7b, 0x9a, 0x58, 0x75, 0x3d, 0xce, 0xcc, 0xa4, 0x52, 0x58, 0xf1, 0x13,
	0xf8, 0x17, 0xf0, 0x3f, 0xd8, 0xb0, 0xec, 0x06, 0xa9, 0x4b, 0xea, 0x6e, 0x58, 0xf6, 0x27, 0xa0,
	0x99, 0x71, 0x3e, 0x5a, 0x2a, 0x2a, 0xb1, 0x9b, 0xb9, 0xe7, 0xdc, 0x73, 0x3c, 0xe7, 0xde, 0x04,
	0x9e, 0x08, 0x1e, 0xb4, 0x03, 0xc2, 0x13, 0x26, 0xdb, 0x01, 0x3b, 0x4e, 0xa3, 0x98, 0xf2, 0xc9,
	0x21, 0xf5, 0xdb, 0x61, 0x24, 0x24, 0x8f, 0xfc, 0xa1, 0xa4, 0xa1, 0x97, 0xc6, 0x24, 0x71, 0x52,
	0xce, 0x24, 0x43, 0xff, 0xa6, 0xb1, 0x63, 0xba, 0x9c, 0x31, 0xd9, 0x99, 0x76, 0xd5, 0xff, 0x99,
	0x51, 0x55, 0x5d, 0xa9, 0xdf, 0x9e, 0x36, 0xd7, 0x9b, 0x0a, 0x95, 0xc4, 0x8f, 0xa9, 0x27, 0x24,
	0xe3, 0xb4, 0xad, 0xcb, 0x6d, 0x11, 0xf4, 0xe9, 0x31, 0x31, 0x9c, 0xe6, 0xb7, 0x22, 0xc0, 0x8e,
	0x16, 0xd8, 0x4b, 0x0e, 0x19, 0x7a, 0x08, 0xb5, 0xc1, 0x90, 0xf2, 0x91, 0xe7, 0x73, 0x76, 0x44,
	0xb9, 0x47, 0xc2, 0x90, 0x53, 0x21, 0x6c, 0xab, 0x61, 0xb5, 0xca, 0x2e, 0xd2, 0xd8, 0xb6, 0x86,
	0xb6, 0x0c, 0x82, 0xee, 0xc0, 0x6a, 0x9f, 0x08, 0xaf, 0xc7, 0xd3, 0xc0, 0x13, 0x94, 0x9f, 0x50,
	0x6e, 0x17, 0x1b, 0x56, 0x6b, 0xc9, 0xfd, 0xab, 0x4f, 0xc4, 0x2e, 0x4f, 0x83, 0xae, 0x2e, 0xa2,
	0x0d, 0x58, 0xd6, 0x9c, 0xb1, 0x62, 0x49, 0x2b, 0x56, 0x54, 0x6d, 0x2c, 0xf5, 0x1f, 0xac, 0x28,
	0xa9, 0x90, 0x48, 0x62, 0x3e, 0xd8, 0x9e, 0xd3, 0x4a, 0xcb, 0x7d, 0x22, 0x3a, 0x44, 0x92, 0xae,
	0xaa, 0xa1, 0xff, 0x61, 0x25, 0xe5, 0x2c, 0xa0, 0x42, 0x50, 0xc3, 0xb5, 0xe7, 0x8d, 0xdf, 0xa4,
	0xaa, 0xb8, 0xe8, 0x31, 0xac, 0x93, 0x20, 0xa0, 0xa9, 0x14, 0x1e, 0xa7, 0xc7, 0x4c, 0x52, 0x4f,
	0xb0, 0x21, 0x0f, 0xa8, 0xb0, 0x17, 0x34, 0xbd, 0x96, 0xa3, 0xae, 0x06, 0xbb, 0x06, 0x43, 0xbb,
	0x00, 0x26, 0xb0, 0x28, 0x39, 0x64, 0xf6, 0x62, 0xa3, 0xd4, 0xaa, 0x6c, 0xb6, 0x9c, 0xdf, 0x0e,
	0xc1, 0xd9, 0x57, 0x0d, 0x2a, 0x3d, 0xb7, 0x2c, 0xc7, 0xc7, 0xe6, 0x27, 0x0b, 0xca, 0x13, 0x00,
	0xd5, 0x60, 0x5e, 0x43, 0x79, 0x8e, 0xe6, 0x82, 0x9e, 0xc3, 0x12, 0xa7, 0x31, 0x91, 0x11, 0x4b,
	0x74, 0x66, 0x95, 0xcd, 0x0d, 0x65, 0x35, 0x33, 0x31, 0xc7, 0xcc, 0x2a, 0xf5, 0x1d, 0x37, 0x27,
	0xba, 0x93, 0x16, 0x74, 0x1f, 0xfe, 0xd6, 0x54, 0x19, 0xbd, 0xd7, 0x05, 0xef, 0x88, 0x8e, 0xf2,
	0x58, 0xab, 0x57, 0x80, 0xd7, 0x74, 0x84, 0x6c, 0x58, 0x34, 0x35, 0x61, 0xcf, 0x35, 0x4a, 0xad,
	0xb2, 0x3b, 0xbe, 0x36, 0xdf, 0x41, 0xb5, 0x33, 0x5d, 0xbe, 0xae, 0x24, 0x92, 0xa2, 0x57, 0x50,
	0x31, 0x0f, 0x36, 0x39, 0x58, 0x3a, 0x87, 0x7b, 0xb7, 0xe4, 0x30, 0x5d, 0x23, 0x17, 0x82, 0xc9,
	0xb9, 0xf9, 0xa5, 0x04, 0xab, 0x33, 0x06, 0x6f, 0x62, 0x92, 0xa0, 0x14, 0xd0, 0xc0, 0x1f, 0xaf,
	0x82, 0x27, 0x99, 0x5e, 0xf9, 0xdc, 0x66, 0xe7, 0x16, 0x9b, 0x6b, 0x5a, 0xce, 0x5b, 0x3f, 0xdf,
	0x9f, 0x7d, 0xa6, 0xee, 0x2f, 0x13, 0xc9, 0x47, 0xee, 0xea, 0xe0, 0x6a, 0x15, 0x49, 0xa8, 0x5d,
	0x75, 0x0c, 0x49, 0xcf, 0x8b, 0x42, 0xbb, 0xa8, 0x3d, 0x3b, 0x7f, 0xee, 0xd9, 0x21, 0xbd, 0xbd,
	0xd0, 0x98, 0x56, 0x07, 0xd7, 0xca, 0xe8, 0x2e, 0x94, 0x42, 0xd2, 0xd3, 0x43, 0xa9, 0x6c, 0xae,
	0xcd, 0x98, 0x98, 0x1f, 0xab, 0xd3, 0xd9, 0xda, 0x75, 0x15, 0xa3, 0x7e, 0x00, 0xb5, 0x9b, 0xde,
	0x81, 0xaa, 0x50, 0x52, 0x53, 0x35, 0x6b, 0xa3, 0x8e, 0xe8, 0x01, 0xcc, 0x9f, 0x90, 0x78, 0x48,
	0xf3, 0x8d, 0x59, 0xff, 0x55, 0x54, 0x75, 0xbb, 0x86, 0xf4, 0xac, 0xf8, 0xd4, 0xaa, 0xef, 0xc0,
	0xda, 0x8d, 0xdf, 0x7b, 0x83, 0x78, 0x6d, 0x56, 0x7c, 0x6e, 0x46, 0x64, 0xfb, 0xc5, 0xe9, 0x39,
	0x2e, 0x9c, 0x9d, 0xe3, 0xc2, 0xe5, 0x39, 0xb6, 0x3e, 0x64, 0xd8, 0xfa, 0x9c, 0x61, 0xeb, 0x6b,
	0x86, 0xad, 0xd3, 0x0c, 0x5b, 0xdf, 0x33, 0x6c, 0xfd, 0xc8, 0x70, 0xe1, 0x32, 0xc3, 0xd6, 0xc7,
	0x0b, 0x5c, 0x38, 0xbd, 0xc0, 0x85, 0xb3, 0x0b, 0x5c, 0x38, 0x80, 0x69, 0x86, 0xfe, 0x82, 0xfe,
	0xc3, 0x79, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x4c, 0x9d, 0x92, 0x0a, 0x05, 0x00, 0x00,
}

func (this *CarnotInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CarnotInfo)
	if !ok {
		that2, ok := that.(CarnotInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.QueryBrokerAddress != that1.QueryBrokerAddress {
		return false
	}
	if this.HasGrpcServer != that1.HasGrpcServer {
		return false
	}
	if this.GrpcAddress != that1.GrpcAddress {
		return false
	}
	if this.HasDataStore != that1.HasDataStore {
		return false
	}
	if this.ProcessesData != that1.ProcessesData {
		return false
	}
	if this.AcceptsRemoteSources != that1.AcceptsRemoteSources {
		return false
	}
	if len(this.TableInfo) != len(that1.TableInfo) {
		return false
	}
	for i := range this.TableInfo {
		if !this.TableInfo[i].Equal(that1.TableInfo[i]) {
			return false
		}
	}
	return true
}
func (this *TableInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TableInfo)
	if !ok {
		that2, ok := that.(TableInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Table != that1.Table {
		return false
	}
	if !this.Relation.Equal(that1.Relation) {
		return false
	}
	if this.TabletizationKey != that1.TabletizationKey {
		return false
	}
	if len(this.Tablets) != len(that1.Tablets) {
		return false
	}
	for i := range this.Tablets {
		if this.Tablets[i] != that1.Tablets[i] {
			return false
		}
	}
	return true
}
func (this *DistributedState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DistributedState)
	if !ok {
		that2, ok := that.(DistributedState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.CarnotInfo) != len(that1.CarnotInfo) {
		return false
	}
	for i := range this.CarnotInfo {
		if !this.CarnotInfo[i].Equal(that1.CarnotInfo[i]) {
			return false
		}
	}
	return true
}
func (this *DistributedPlan) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DistributedPlan)
	if !ok {
		that2, ok := that.(DistributedPlan)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.QbAddressToPlan) != len(that1.QbAddressToPlan) {
		return false
	}
	for i := range this.QbAddressToPlan {
		if !this.QbAddressToPlan[i].Equal(that1.QbAddressToPlan[i]) {
			return false
		}
	}
	if len(this.QbAddressToDagId) != len(that1.QbAddressToDagId) {
		return false
	}
	for i := range this.QbAddressToDagId {
		if this.QbAddressToDagId[i] != that1.QbAddressToDagId[i] {
			return false
		}
	}
	if !this.Dag.Equal(that1.Dag) {
		return false
	}
	return true
}
func (this *CarnotInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&compilerpb.CarnotInfo{")
	s = append(s, "QueryBrokerAddress: "+fmt.Sprintf("%#v", this.QueryBrokerAddress)+",\n")
	s = append(s, "HasGrpcServer: "+fmt.Sprintf("%#v", this.HasGrpcServer)+",\n")
	s = append(s, "GrpcAddress: "+fmt.Sprintf("%#v", this.GrpcAddress)+",\n")
	s = append(s, "HasDataStore: "+fmt.Sprintf("%#v", this.HasDataStore)+",\n")
	s = append(s, "ProcessesData: "+fmt.Sprintf("%#v", this.ProcessesData)+",\n")
	s = append(s, "AcceptsRemoteSources: "+fmt.Sprintf("%#v", this.AcceptsRemoteSources)+",\n")
	if this.TableInfo != nil {
		s = append(s, "TableInfo: "+fmt.Sprintf("%#v", this.TableInfo)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TableInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&compilerpb.TableInfo{")
	s = append(s, "Table: "+fmt.Sprintf("%#v", this.Table)+",\n")
	if this.Relation != nil {
		s = append(s, "Relation: "+fmt.Sprintf("%#v", this.Relation)+",\n")
	}
	s = append(s, "TabletizationKey: "+fmt.Sprintf("%#v", this.TabletizationKey)+",\n")
	s = append(s, "Tablets: "+fmt.Sprintf("%#v", this.Tablets)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DistributedState) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&compilerpb.DistributedState{")
	if this.CarnotInfo != nil {
		s = append(s, "CarnotInfo: "+fmt.Sprintf("%#v", this.CarnotInfo)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DistributedPlan) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&compilerpb.DistributedPlan{")
	keysForQbAddressToPlan := make([]string, 0, len(this.QbAddressToPlan))
	for k, _ := range this.QbAddressToPlan {
		keysForQbAddressToPlan = append(keysForQbAddressToPlan, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForQbAddressToPlan)
	mapStringForQbAddressToPlan := "map[string]*planpb.Plan{"
	for _, k := range keysForQbAddressToPlan {
		mapStringForQbAddressToPlan += fmt.Sprintf("%#v: %#v,", k, this.QbAddressToPlan[k])
	}
	mapStringForQbAddressToPlan += "}"
	if this.QbAddressToPlan != nil {
		s = append(s, "QbAddressToPlan: "+mapStringForQbAddressToPlan+",\n")
	}
	keysForQbAddressToDagId := make([]string, 0, len(this.QbAddressToDagId))
	for k, _ := range this.QbAddressToDagId {
		keysForQbAddressToDagId = append(keysForQbAddressToDagId, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForQbAddressToDagId)
	mapStringForQbAddressToDagId := "map[string]uint64{"
	for _, k := range keysForQbAddressToDagId {
		mapStringForQbAddressToDagId += fmt.Sprintf("%#v: %#v,", k, this.QbAddressToDagId[k])
	}
	mapStringForQbAddressToDagId += "}"
	if this.QbAddressToDagId != nil {
		s = append(s, "QbAddressToDagId: "+mapStringForQbAddressToDagId+",\n")
	}
	if this.Dag != nil {
		s = append(s, "Dag: "+fmt.Sprintf("%#v", this.Dag)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringDistributedPlan(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CarnotInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CarnotInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.QueryBrokerAddress) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(len(m.QueryBrokerAddress)))
		i += copy(dAtA[i:], m.QueryBrokerAddress)
	}
	if m.HasGrpcServer {
		dAtA[i] = 0x10
		i++
		if m.HasGrpcServer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.GrpcAddress) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(len(m.GrpcAddress)))
		i += copy(dAtA[i:], m.GrpcAddress)
	}
	if m.HasDataStore {
		dAtA[i] = 0x20
		i++
		if m.HasDataStore {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.ProcessesData {
		dAtA[i] = 0x28
		i++
		if m.ProcessesData {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.AcceptsRemoteSources {
		dAtA[i] = 0x30
		i++
		if m.AcceptsRemoteSources {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.TableInfo) > 0 {
		for _, msg := range m.TableInfo {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintDistributedPlan(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *TableInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TableInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Table) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(len(m.Table)))
		i += copy(dAtA[i:], m.Table)
	}
	if m.Relation != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(m.Relation.Size()))
		n1, err := m.Relation.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.TabletizationKey) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(len(m.TabletizationKey)))
		i += copy(dAtA[i:], m.TabletizationKey)
	}
	if len(m.Tablets) > 0 {
		for _, s := range m.Tablets {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *DistributedState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DistributedState) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.CarnotInfo) > 0 {
		for _, msg := range m.CarnotInfo {
			dAtA[i] = 0xa
			i++
			i = encodeVarintDistributedPlan(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *DistributedPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DistributedPlan) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.QbAddressToPlan) > 0 {
		for k, _ := range m.QbAddressToPlan {
			dAtA[i] = 0xa
			i++
			v := m.QbAddressToPlan[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovDistributedPlan(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovDistributedPlan(uint64(len(k))) + msgSize
			i = encodeVarintDistributedPlan(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintDistributedPlan(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintDistributedPlan(dAtA, i, uint64(v.Size()))
				n2, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n2
			}
		}
	}
	if len(m.QbAddressToDagId) > 0 {
		for k, _ := range m.QbAddressToDagId {
			dAtA[i] = 0x12
			i++
			v := m.QbAddressToDagId[k]
			mapSize := 1 + len(k) + sovDistributedPlan(uint64(len(k))) + 1 + sovDistributedPlan(uint64(v))
			i = encodeVarintDistributedPlan(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintDistributedPlan(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x10
			i++
			i = encodeVarintDistributedPlan(dAtA, i, uint64(v))
		}
	}
	if m.Dag != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDistributedPlan(dAtA, i, uint64(m.Dag.Size()))
		n3, err := m.Dag.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func encodeVarintDistributedPlan(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CarnotInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryBrokerAddress)
	if l > 0 {
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	if m.HasGrpcServer {
		n += 2
	}
	l = len(m.GrpcAddress)
	if l > 0 {
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	if m.HasDataStore {
		n += 2
	}
	if m.ProcessesData {
		n += 2
	}
	if m.AcceptsRemoteSources {
		n += 2
	}
	if len(m.TableInfo) > 0 {
		for _, e := range m.TableInfo {
			l = e.Size()
			n += 1 + l + sovDistributedPlan(uint64(l))
		}
	}
	return n
}

func (m *TableInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Table)
	if l > 0 {
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	if m.Relation != nil {
		l = m.Relation.Size()
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	l = len(m.TabletizationKey)
	if l > 0 {
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	if len(m.Tablets) > 0 {
		for _, s := range m.Tablets {
			l = len(s)
			n += 1 + l + sovDistributedPlan(uint64(l))
		}
	}
	return n
}

func (m *DistributedState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CarnotInfo) > 0 {
		for _, e := range m.CarnotInfo {
			l = e.Size()
			n += 1 + l + sovDistributedPlan(uint64(l))
		}
	}
	return n
}

func (m *DistributedPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.QbAddressToPlan) > 0 {
		for k, v := range m.QbAddressToPlan {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovDistributedPlan(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovDistributedPlan(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovDistributedPlan(uint64(mapEntrySize))
		}
	}
	if len(m.QbAddressToDagId) > 0 {
		for k, v := range m.QbAddressToDagId {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDistributedPlan(uint64(len(k))) + 1 + sovDistributedPlan(uint64(v))
			n += mapEntrySize + 1 + sovDistributedPlan(uint64(mapEntrySize))
		}
	}
	if m.Dag != nil {
		l = m.Dag.Size()
		n += 1 + l + sovDistributedPlan(uint64(l))
	}
	return n
}

func sovDistributedPlan(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDistributedPlan(x uint64) (n int) {
	return sovDistributedPlan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CarnotInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CarnotInfo{`,
		`QueryBrokerAddress:` + fmt.Sprintf("%v", this.QueryBrokerAddress) + `,`,
		`HasGrpcServer:` + fmt.Sprintf("%v", this.HasGrpcServer) + `,`,
		`GrpcAddress:` + fmt.Sprintf("%v", this.GrpcAddress) + `,`,
		`HasDataStore:` + fmt.Sprintf("%v", this.HasDataStore) + `,`,
		`ProcessesData:` + fmt.Sprintf("%v", this.ProcessesData) + `,`,
		`AcceptsRemoteSources:` + fmt.Sprintf("%v", this.AcceptsRemoteSources) + `,`,
		`TableInfo:` + strings.Replace(fmt.Sprintf("%v", this.TableInfo), "TableInfo", "TableInfo", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TableInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TableInfo{`,
		`Table:` + fmt.Sprintf("%v", this.Table) + `,`,
		`Relation:` + strings.Replace(fmt.Sprintf("%v", this.Relation), "Relation", "proto1.Relation", 1) + `,`,
		`TabletizationKey:` + fmt.Sprintf("%v", this.TabletizationKey) + `,`,
		`Tablets:` + fmt.Sprintf("%v", this.Tablets) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DistributedState) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DistributedState{`,
		`CarnotInfo:` + strings.Replace(fmt.Sprintf("%v", this.CarnotInfo), "CarnotInfo", "CarnotInfo", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DistributedPlan) String() string {
	if this == nil {
		return "nil"
	}
	keysForQbAddressToPlan := make([]string, 0, len(this.QbAddressToPlan))
	for k, _ := range this.QbAddressToPlan {
		keysForQbAddressToPlan = append(keysForQbAddressToPlan, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForQbAddressToPlan)
	mapStringForQbAddressToPlan := "map[string]*planpb.Plan{"
	for _, k := range keysForQbAddressToPlan {
		mapStringForQbAddressToPlan += fmt.Sprintf("%v: %v,", k, this.QbAddressToPlan[k])
	}
	mapStringForQbAddressToPlan += "}"
	keysForQbAddressToDagId := make([]string, 0, len(this.QbAddressToDagId))
	for k, _ := range this.QbAddressToDagId {
		keysForQbAddressToDagId = append(keysForQbAddressToDagId, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForQbAddressToDagId)
	mapStringForQbAddressToDagId := "map[string]uint64{"
	for _, k := range keysForQbAddressToDagId {
		mapStringForQbAddressToDagId += fmt.Sprintf("%v: %v,", k, this.QbAddressToDagId[k])
	}
	mapStringForQbAddressToDagId += "}"
	s := strings.Join([]string{`&DistributedPlan{`,
		`QbAddressToPlan:` + mapStringForQbAddressToPlan + `,`,
		`QbAddressToDagId:` + mapStringForQbAddressToDagId + `,`,
		`Dag:` + strings.Replace(fmt.Sprintf("%v", this.Dag), "DAG", "planpb.DAG", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringDistributedPlan(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CarnotInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributedPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CarnotInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CarnotInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryBrokerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryBrokerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasGrpcServer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasGrpcServer = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrpcAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrpcAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasDataStore", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasDataStore = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessesData", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ProcessesData = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptsRemoteSources", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AcceptsRemoteSources = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TableInfo = append(m.TableInfo, &TableInfo{})
			if err := m.TableInfo[len(m.TableInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributedPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TableInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributedPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TableInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TableInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Table", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Table = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Relation == nil {
				m.Relation = &proto1.Relation{}
			}
			if err := m.Relation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TabletizationKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TabletizationKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tablets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tablets = append(m.Tablets, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributedPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DistributedState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributedPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DistributedState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DistributedState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CarnotInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CarnotInfo = append(m.CarnotInfo, &CarnotInfo{})
			if err := m.CarnotInfo[len(m.CarnotInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributedPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DistributedPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributedPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DistributedPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DistributedPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QbAddressToPlan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QbAddressToPlan == nil {
				m.QbAddressToPlan = make(map[string]*planpb.Plan)
			}
			var mapkey string
			var mapvalue *planpb.Plan
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDistributedPlan
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDistributedPlan
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDistributedPlan
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &planpb.Plan{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDistributedPlan(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.QbAddressToPlan[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QbAddressToDagId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QbAddressToDagId == nil {
				m.QbAddressToDagId = make(map[string]uint64)
			}
			var mapkey string
			var mapvalue uint64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDistributedPlan
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDistributedPlan
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDistributedPlan
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDistributedPlan(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthDistributedPlan
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.QbAddressToDagId[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dag", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dag == nil {
				m.Dag = &planpb.DAG{}
			}
			if err := m.Dag.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributedPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDistributedPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDistributedPlan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDistributedPlan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributedPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDistributedPlan
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthDistributedPlan
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDistributedPlan
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDistributedPlan(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthDistributedPlan
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDistributedPlan = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDistributedPlan   = fmt.Errorf("proto: integer overflow")
)
