apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "pl-etcd"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.4.3"
  pod:
    etcdEnv:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "10"
    - name: ETCD_AUTO_COMPACTION_MODE
      value: "revision"
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls-certs
        serverSecret: etcd-server-tls-certs
      operatorSecret: etcd-client-tls-certs
