workspace(name = "privy")

local_repository(
    name = "px",
    path = "../../../../",
)

load("@px//bazel:repositories.bzl", "pl_deps")

pl_deps()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "privy_deps",
    requirements_lock = "//:requirements.bazel.txt",
)

load("@privy_deps//:requirements.bzl", privy_install_deps = "install_deps")

privy_install_deps()
