---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
resources:
- ../../base/elastic/cluster
patches:
- path: elastic_creds.yaml
  target:
    kind: Elasticsearch
- path: node_selector_patch.yaml
  target:
    kind: Elasticsearch
- path: elastic_storage_patch.yaml
  target:
    group: elasticsearch.k8s.elastic.co
    kind: Elasticsearch
    name: pl-elastic
    version: v1
labels:
- includeSelectors: true
  pairs:
    app: pl-cloud
