---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: px-protocol-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: app
        image: protocol_loadtest_server_image:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTP_SSL_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9080"
        - name: GRPC_SSL_PORT
          value: "9081"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: https
        - containerPort: 9080
          name: grpc
        - containerPort: 9081
          name: grpcs
