# Docker file for development environment and build.
# We can also make small environment changes here, if we want to prevent large changes
# that make building on Jenkins slow. Over time most changes in this file should
# be moved to the base image.
FROM gcr.io/pl-dev-infra/base_dev_image:201808211617

CMD ["/bin/bash"]
