---
name: Use buildbuddy bazel config
description: Adds BES support to the bazelrc for connecting to bb.px.dev
inputs:
  bb_api_key:
    required: true
    type: string
runs:
  using: "composite"
  steps:
  - name: Copy BES bazel config
    run: |
      cp ci/bes-oss-gce.bazelrc bes.bazelrc
      echo "build --remote_header=x-buildbuddy-api-key=${{ inputs.bb_api_key }}" >> bes.bazelrc
      echo "build --build_metadata=USER=github-actions" >> bes.bazelrc
    shell: bash
