---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
resources:
- clusterroles
- ../../base/nats
labels:
- includeSelectors: true
  pairs:
    app: pl-cloud
    component: cloud-deps
patches:
- path: storage_patch.yaml
