---
name: main-cacher
on:
  push:
    branches:
    - 'main'
permissions:
  contents: read
jobs:
  get-dev-image:
    uses: ./.github/workflows/get_image.yaml
    with:
      image-base-name: "dev_image"
  populate-caches:
    runs-on: ubuntu-latest-8-cores
    needs: get-dev-image
    container:
      image: ${{ needs.get-dev-image.outputs.image-with-tag }}
      options: --cpus 7
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: go cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf  # v4.2.2
      with:
        path: /px/pkg/mod
        key: go-cache-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-cache-
    - name: yarn cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf  # v4.2.2
      with:
        path: ./src/ui/.yarn/cache
        key: yarn-cache-${{ hashFiles('src/ui/yarn.lock', 'src/ui/.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-
    - shell: bash
      run: |
        go mod download;
        pushd src/ui > /dev/null;
        yarn install;
        popd > /dev/null;
