---
name: 'fossa'
on:
  push:
    branches:
    - 'main'
permissions:
  contents: read
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: fossas/fossa-action@93a52ecf7c3ac7eb40f5de77fd69b1a19524de94  # v1.5.0
      with:
        api-key: ${{ secrets.FOSSA_API_KEY }}
