---
name: mirror-demos
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  sync_demos:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest-16-cores
    steps:
    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USER }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34  # v5.3.0
      with:
        go-version-file: 'go.mod'
    - name: install regbot
      shell: bash
      run: go install github.com/regclient/regclient/cmd/regbot@v0.4.8
    - name: sync images
      shell: bash
      run: |
        cd scripts/regclient
        regbot once --config regbot_demos.yaml
