---
name: pr-description-linter
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  lint-pr-description:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      PR_BODY: ${{github.event.pull_request.body}}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - id: run-pr-description-linter
      run: ./tools/linters/pr_description_linter.sh
