---
name: vizier-release
on:
  push:
    tags:
    - release/vizier/**
permissions:
  contents: read
env:
  VERSIONS_FILE: "VERSIONS.json"
jobs:
  get-dev-image:
    uses: ./.github/workflows/get_image.yaml
    with:
      image-base-name: "dev_image_with_extras"
  build-release:
    name: Build Release
    runs-on: [self-hosted, nokvm]
    needs: get-dev-image
    container:
      image: ${{ needs.get-dev-image.outputs.image-with-tag }}
      options: --cpus 15
      volumes:
      - /etc/bazelrc:/etc/bazelrc
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0
      with:
        fetch-depth: 0
    - name: Add pwd to git safe dir
      run: git config --global --add safe.directory `pwd`
    - name: Setup gcloud docker creds
      run: gcloud init && gcloud auth configure-docker
    - name: Use github bazel config
      uses: ./.github/actions/bazelrc
    - name: Build & Push Artifacts
      env:
        REF: ${{ github.event.ref }}
        BUILD_NUMBER: ${{ github.run_attempt }}
        JOB_NAME: ${{ github.job }}
      shell: bash
      run: |
        export TAG_NAME="${REF#*/tags/}"
        export ARTIFACTS_DIR="$(pwd)/artifacts"
        mkdir -p "${ARTIFACTS_DIR}"
        ./ci/save_version_info.sh
        ./ci/vizier_build_release.sh
    - name: Build & Export Docs
      env:
        PXL_DOCS_GCS_PATH: "gs://pixie-dev-public/pxl-docs.json"
      run: |
        docs="$(mktemp)"
        bazel run //src/carnot/docstring:docstring -- --output_json "${docs}"
        gsutil cp "${docs}" "${PXL_DOCS_GCS_PATH}"
    - name: Update Manifest
      env:
        ARTIFACT_MANIFEST_BUCKET: "pixie-dev-public"
      run: ./ci/update_artifact_manifest.sh
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce  # v3.1.2
      with:
        name: vizier-artifacts
        path: artifacts/
  create-github-release:
    if: ${{ !contains(github.event.ref, '-') }}
    name: Create Release on Github
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write
    outputs:
      release-url: ${{ steps.release.outputs.url }}
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a  # v3.0.2
    - name: Create Release
      id: release
      env:
        REF: ${{ github.event.ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: pixie-io
        REPO: pixie
      shell: bash
      # yamllint disable rule:indentation
      run: |
        export TAG_NAME="${REF#*/tags/}"
        # actions/checkout doesn't get the tag annotation properly.
        git fetch origin tag "${TAG_NAME}" -f
        export changelog="$(git tag -l --format='%(contents)' "${TAG_NAME}")"
        gh release create "${TAG_NAME}" --title "Vizier ${TAG_NAME#release/vizier/}" \
          --notes $'Pixie Vizier Release:\n'"${changelog}"
        gh release upload "${TAG_NAME}" vizier-artifacts/*
        url="$(gh release view "${TAG_NAME}" -q '.url' --json url)"
        echo "url=${url}" >> $GITHUB_OUTPUT
      # yamllint enable rule:indentation
  update-readme:
    name: Update README with latest release
    runs-on: ubuntu-latest
    needs: create-github-release
    permissions:
      contents: read
    # Only run one update readme job at a time.
    concurrency: update-readme
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0
      with:
        ref: main
    - uses: ./.github/actions/update_readme_releases
      with:
        component-name: "vizier"
        release-url: ${{ needs.create-github-release.outputs.release-url }}
        ref: ${{ github.event.ref }}
        BUILDBOT_GH_API_TOKEN: ${{ secrets.BUILDBOT_GH_API_TOKEN }}
        BUILDBOT_GPG_KEY_B64: ${{ secrets.BUILDBOT_GPG_KEY_B64 }}
        BUILDBOT_GPG_KEY_ID: ${{ secrets.BUILDBOT_GPG_KEY_ID }}
        BUILDBOT_SSH_KEY_B64: ${{ secrets.BUILDBOT_SSH_KEY_B64 }}
