---
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/cloud/api_server_image
    context: .
    bazel:
      target: //src/cloud/api:api_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/auth_server_image
    context: .
    bazel:
      target: //src/cloud/auth:auth_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/profile_server_image
    context: .
    bazel:
      target: //src/cloud/profile:profile_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/proxy_server_image
    context: .
    bazel:
      target: //src/cloud/proxy:proxy_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/plugin_server_image
    context: .
    bazel:
      target: //src/cloud/plugin:plugin_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/project_manager_server_image
    context: .
    bazel:
      target: //src/cloud/project_manager:project_manager_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/config_manager_server_image
    context: .
    bazel:
      target: //src/cloud/config_manager:config_manager_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/vzconn_server_image
    context: .
    bazel:
      target: //src/cloud/vzconn:vzconn_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/vzmgr_server_image
    context: .
    bazel:
      target: //src/cloud/vzmgr:vzmgr_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/indexer_server_image
    context: .
    bazel:
      target: //src/cloud/indexer:indexer_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/artifact_tracker_server_image
    context: .
    bazel:
      target: //src/cloud/artifact_tracker:artifact_tracker_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/scriptmgr_server_image
    context: .
    bazel:
      target: //src/cloud/scriptmgr:scriptmgr_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/cron_script_server_image
    context: .
    bazel:
      target: //src/cloud/cron_script:cron_script_server_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/plugin/load_db
    context: .
    bazel:
      target: //src/cloud/plugin/load_db:plugin_db_updater_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/cloud/metrics_server_image
    context: .
    bazel:
      target: //src/cloud/metrics:metrics_server_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
manifests:
  kustomize:
    paths:
    - k8s/cloud/dev
profiles:
- name: minikube
  activation:
  - kubeContext: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
- name: dev
  activation:
  - command: dev
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
- name: ory_auth
  patches:
  - op: replace
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/dev
    - k8s/cloud/dev/ory_auth
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
- name: ory_auth_prod
  patches:
  - op: add
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/base/ory_auth
- name: staging
  activation:
  - env: PL_BUILD_TYPE=staging
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --config=stamp
    - --action_env=GOOGLE_APPLICATION_CREDENTIALS
  - op: replace
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/staging
- name: testing
  activation:
  - env: PL_BUILD_TYPE=testing
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --config=stamp
    - --action_env=GOOGLE_APPLICATION_CREDENTIALS
  - op: replace
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/testing
- name: prod
  activation:
  - env: PL_BUILD_TYPE=prod
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --config=stamp
    - --action_env=GOOGLE_APPLICATION_CREDENTIALS
  - op: replace
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/prod
- name: public
  patches:
  - op: replace
    path: /manifests/kustomize/paths
    value:
    - k8s/cloud/public/base
