apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev-public/cloud/stan_watcher_image
    context: .
    bazel:
      target: //src/cloud/utils/stan_watcher:stan_watcher_image.tar
  tagPolicy:
    dateTime: {}
deploy:
  kustomize:
    paths:
    - k8s/utils/dev/cloud_stan_nats_watcher
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
