apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pl-dev-infra/cloud/api_server_image
    context: .
    bazel:
      target: //src/cloud/api:api_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/auth_server_image
    context: .
    bazel:
      target: //src/cloud/auth:auth_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/profile_server_image
    context: .
    bazel:
      target: //src/cloud/profile:profile_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/proxy_server_image
    context: .
    bazel:
      target: //src/cloud/proxy:proxy_prod_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/project_manager_server_image
    context: .
    bazel:
      target: //src/cloud/project_manager:project_manager_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/vzconn_server_image
    context: .
    bazel:
      target: //src/cloud/vzconn:vzconn_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/vzmgr_server_image
    context: .
    bazel:
      target: //src/cloud/vzmgr:vzmgr_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/dnsmgr_server_image
    context: .
    bazel:
      target: //src/cloud/dnsmgr:dnsmgr_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/indexer_server_image
    context: .
    bazel:
      target: //src/cloud/indexer:indexer_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/artifact_tracker_server_image
    context: .
    bazel:
      target: //src/cloud/artifact_tracker:artifact_tracker_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/scriptmgr_server_image
    context: .
    bazel:
      target: //src/cloud/scriptmgr:scriptmgr_server_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - k8s/cloud/dev
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
- name: dev
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
  activation:
  - command: dev
- name: nightly
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
  - op: add
    path: /build/tagPolicy
    value:
      dateTime: null
      envTemplate:
        template: '{{.IMAGE_NAME}}:{{.PL_IMAGE_TAG}}'
  - op: replace
    path: /deploy/kustomize
    value:
      path: k8s/cloud/nightly
  activation:
  - env: PL_BUILD_TYPE=nightly
- name: staging
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --stamp
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/staging]
  activation:
  - env: PL_BUILD_TYPE=staging
- name: prod_old
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/prod]
  activation:
  - env: PL_BUILD_TYPE=prod_old
- name: prod
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --stamp
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/prod]
  activation:
  - env: PL_BUILD_TYPE=prod
- name: testing
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
  - op: replace
    path: /deploy/kustomize
    value:
      path: k8s/cloud/testing
  activation:
  - env: PL_BUILD_TYPE=testing
