---
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: operator-operator_image
    context: .
    bazel:
      target: //src/operator:operator_image.tar
  tagPolicy:
    dateTime: {}
manifests:
  kustomize:
    paths:
    - k8s/operator/deployment/base/
profiles:
- name: minikube
  activation:
  - kubeContext: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
